included:
  - iOSEngineerCodeCheck/

disabled_rules:
  - line_length
  - function_parameter_count
  - force_cast
  - force_try
  - nesting
  - superfluous_disable_command
  - generic_type_name

opt_in_rules:
  - explicit_init
  - empty_count
  - overridden_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - closure_spacing
  - contains_over_first_not_nil
  - first_where
  - last_where
  - literal_expression_end_indentation
  - private_action
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - attributes
  - collection_alignment
  - empty_string
  - legacy_random
  - let_var_whitespace
  - operator_usage_whitespace
  - static_operator
  - toggle_bool
  - unused_import
  - unused_declaration

trailing_whitespace:
  ignores_empty_lines: true # 改行時にxcodeが自動でインデントタブ入れるので許容する

type_name:
  min_length:
    warning: 2
  max_length:
    warning: 45
    error: 60

trailing_comma:
  # リテラル表記を要素毎に改行している場合、最後の要素に必ずcommaを付ける
  mandatory_comma: false

identifier_name:
  min_length:
    warning: 1
  allowed_symbols: [_] # private変数のprefixに"_"を付けることを許容するため
  validates_start_with_lowercase: false # private変数のprefixに"_"を付けることを許容するため

cyclomatic_complexity:
  warning: 10
  error: 15
  ignores_case_statements: true # Reducerの定義上、Actionに応じてswitchで分岐していくので, switchは計算しない

file_length:
  warning: 500
  error: 800

type_body_length:
  warning: 500

function_body_length:
  warning: 50

large_tuple:
  warning: 4